name = "Spikes"
uuid = "a305d8b4-9cce-41f7-8708-a71367dc1260"
authors = ["Stefano Bettani <bettani@bio.ens.pls.eu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
